name: nathanielxd
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  intl: ^0.18.0
  yaml: ^3.1.2
  flutter_animate: ^4.4.0
  flutter_markdown: ^0.6.23

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/
    - assets/carousel/
    - assets/backgrounds/

  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope.ttf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans.ttf
    - family: RedditMono
      fonts:
        - asset: fonts/RedditMono.ttf
    - family: BebasNeue
      fonts:
        - asset: fonts/BebasNeue.ttf
