name: nathanielxd
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  intl: ^0.18.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  yaml: ^3.1.2
  go_router: ^13.0.1
  flutter_animate: ^4.4.0
  flutter_markdown: ^0.6.23

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope.ttf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans.ttf
    - family: RedditMono
      fonts:
        - asset: fonts/RedditMono.ttf
